### PR TITLE
Setup dev enviroment Assignment

### PR DESCRIPTION
**Pull request by devoob326**

### CODE REVIEW

**Comment by devoob326** [comment]
@CodiumAI-Agent/review

**Comment by devoob326** [comment]
@CodiumAI-Agent/review

**Comment by th3c0d3br34ker** [comment]
hey @devoob326 you are missing a 'space' in between, it should be `@CodiumAI-Agent /review`

**Comment by devoob326** [comment]
@CodiumAI-Agent /review

**Pull request merged**
